version: "3"

services:
  app:
  #acionar node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=mtripolone
        - UID=1000
    user: mtripolone
    container_name: app-shipping
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # nginx
  nginx:
    container_name: webserver-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  mysql:
    container_name: database-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shipping
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - laravel

  #DB Panel
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8001:8080
    networks:
      - laravel

  #Redis DB
  redis-compose:
    image: redis
    container_name: redis-compose
    command: redis-server --requirepass password --appendonly yes
    hostname: redis
    ports:
      - "8002:6379"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
